# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 024b97811a000ab05920495ca7701c9a7e66b2509a6a1c2f117dddf580edf61fc185118ae80eda046c21929f0201e01f6ccd7724f086e23c21cbeaa73f091e6a

test:
  secret_key_base: 15713f0c0af2f7df05b4ecf0227bc9eee2209e1599adcf2086699808c8b1053f58e7e1122fdac6cbb0b3e40d2e3153fc2182515802002e5182b19c1242fadf7f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
